# 工作流名称
name: Auto Sign

# 工作流触发条件
on:
  # 定时触发：设置为每天UTC时间1点整（对应北京时间上午9点）
  schedule:
    - cron: '0 1 * * *'
  
  # 手动触发：允许你在 Actions 页面手动运行此工作流
  workflow_dispatch:

# 工作流任务
jobs:
  build:
    # 运行环境：使用最新的 Ubuntu 系统
    runs-on: ubuntu-latest

    # 任务步骤
    steps:
      # 第一步：检出你的仓库代码
      - uses: actions/checkout@v2

      # 第二步：设置 Python 3.8 环境
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # 第三步：安装依赖项
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 第四步：运行签到脚本
      - name: Run skyland.py
        env:
          # 这是脚本真正需要的环境变量。它会读取名为 TOKEN 的 Secret。
          # 如果有多个 token，请在 Secret 中用英文逗号(,)隔开。
          TOKEN: ${{ secrets.TOKEN }}
          
          # (可选) 开启此项后，如果任何一个账号签到失败，整个任务会标记为失败，并发送邮件通知。
          EXIT_WHEN_FAIL: on
        run: |
          python skyland.py
