# The name of your workflow.
name: Auto Sign

# Controls when the action will run.
on:
  # Triggers the workflow at a scheduled time.
  # This is set to run at 01:00 UTC every day, which is 09:00 Beijing Time.
  schedule:
    - cron: '0 1 * * *'
  
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

      # Sets up a Python 3.8 environment for you to use.
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Installs the dependencies listed in requirements.txt.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Runs the Python script.
      - name: Run skyland.py
        env:
          # This line is crucial. It reads the secret named CONFIG_JSON 
          # and makes it available to the python script as an environment variable.
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          python skyland.py
